### ISSUE TITLE
Support Batch-insert

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/cineast#3]
As far as I understand the code base does currently not support batch inserts into ADAMpro. This is unfortunate for the use case where i want to insert my labels and have to perform one request per key-value pair because the current pers

Did I miss functionality here or is that something that is on the wishlist?

**Comment by lucaro** [comment]
This concerns ADAMpro and not Cineast so this is the wrong place for this issue. Such functionality is however planned for the near future.

**Comment by silvanheller** [comment]
After looking at the protofile some more I think its already possible. 
See 1f77e8217cc2a137c55026d4e27e97b16070edee for the implementation and d7c57945ed59b07aca68c6c2bb4dd42fd421f3fd for usage in label-insertion. This pushes insertion time for 20k elements from ca. 20 minutes to <5 seconds on my laptop
