### ISSUE TITLE
Include the new ADAMpro-Protobuf repo in the devbranch

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/cineast#7]
Currently there are only generated files. It might be worth to switch back to the old subrepo system or include instructions to generate new ADAMpro-Protobuf Files.

Specifically, there are multiple fixes internally which depend on the new ADAMpro-API which are relevant for the GC-Issue we ran into during extraction.

**Comment by lucaro** [comment]
should be synchronized again in 
https://github.com/dbisUnibas/cineast/commit/0dbd16feb01dec2dfecad43e3cd5e760b0083408

**Comment by silvanheller** [comment]
Will test once i get a new docker-conatiner
