### ISSUE TITLE
JSONFileWriter open() removes existing data

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/cineast#8]
The open()-call generates a new PrintWriter which will truncate the existing File to zero (see http://docs.oracle.com/javase/7/docs/api/java/io/PrintWriter.html#PrintWriter(java.io.File))

This means that calling open() twice during an extraction-job will delete extracted data. We should probably use another constructor for the PrintWriter, [for example as described here](http://stackoverflow.com/questions/1625234/how-to-append-text-to-an-existing-file-in-java)

**Comment by lucaro** [comment]
I see that this behavior is not consistent among different implementations of PersistencyWriter. It is however consistent among the implementations which write to files. Appending to existing files could cause files to become invalid, especially in the case of the JsonFileWriter which initializes a JSON array (by printing '[') on open.
Calling open() more than once is also not the intended use.

**Comment by lucaro** [comment]
JSONFileWriters can no longer be opened twice, see https://github.com/dbisUnibas/cineast/commit/c83c89f1e3a60e4eff116798edb5d9d33f529134
